version: '3.7'

services:
  mongo1:
    image: mongo
    restart: always
    command: mongod --replSet rs0 --port 27017 --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - mongo-network
    volumes:
      - mongo1-data:/data/db

  mongo2:
    image: mongo
    restart: always
    command: mongod --replSet rs0 --port 27018 --bind_ip_all
    ports:
      - "27018:27018"
    networks:
      - mongo-network
    volumes:
      - mongo2-data:/data/db

  mongo3:
    image: mongo
    restart: always
    command: mongod --replSet rs0 --port 27019 --bind_ip_all
    ports:
      - "27019:27019"
    networks:
      - mongo-network
    volumes:
      - mongo3-data:/data/db

networks:
  mongo-network:

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
